global:
  scrape_interval: 5m
  scrape_timeout: 1m

scrape_configs:
  - job_name: prometheus
    scheme: http
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 1m
    static_configs:
      - targets: ["127.0.0.1:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prometheus

  - job_name: prometheus_local
    scheme: http
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 2m
    static_configs:
      - targets: ["localhost:9090"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prometheus_local

  - job_name: cloudwatch_exporter
    scheme: https
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 1m
    static_configs:
      - targets: ["cwe.demo.spacerocket.dev"] # Port from tfvars of cloudwatch exporter
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: cloudwatch_exporter

  - job_name: app1
    scheme: https
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 1m
    static_configs:
      - targets: ["app1.demo.spacerocket.dev", "localhost:9091"] # Port from tfvars of app
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: app1
